apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: kube-port-forward-controller
  annotations:
    kube-port-forward-controller/ports: "http:1234"
spec:
  selector:
    app: test-service
  ports:
    - protocol: TCP
      name: http
      port: 81
      targetPort: 81
  loadBalancerIP: 192.168.27.130
  type: LoadBalancer
