###
### Creates a single rule `namespace/web-service:http` that forwards the WAN port 8888 to service port named "http" (1234)
###
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  annotations:
    unifi-port-forward.fiskhe.st/mapping: "8888:http"
spec:
  selector:
    app: web-service
  ports:
    - name: http
      port: 1234
      targetPort: 80
  type: LoadBalancer
###
### Creates a single rule `namespace/web-service2:http` that forwards the WAN port 3000 to service port named "http" (uses the same on both ends)
###
---
apiVersion: v1
kind: Service
metadata:
  name: web-service2
  annotations:
    unifi-port-forward.fiskhe.st/mapping: "http"
spec:
  selector:
    app: web-service2
  ports:
    - name: http
      port: 3000
      targetPort: 8080
  type: LoadBalancer
