###
### Creates a single rule `namespace/web-service:http` that forwards the WAN port 80 to service port named "http"
###
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  annotations:
    unifi-port-forward.fiskhe.st/ports: "89:http,91:https"
spec:
  selector:
    app: web-service
  ports:
    - name: http
      port: 8080
      targetPort: 80
    - name: https
      port: 8181
      targetPort: 80
  type: LoadBalancer
###
### Creates a single rule `namespace/web-service:http` that forwards the WAN port 3000 to service port named "http" (uses same port)
###
---
apiVersion: v1
kind: Service
metadata:
  name: web-service2
  annotations:
    unifi-port-forward.fiskhe.st/ports: "3001:http"
spec:
  selector:
    app: web-service2
  ports:
    - name: http
      port: 3000
      targetPort: 8080
  type: LoadBalancer
